// Generated by gencpp from file camera_pkg/CameraDataRequest.msg
// DO NOT EDIT!


#ifndef CAMERA_PKG_MESSAGE_CAMERADATAREQUEST_H
#define CAMERA_PKG_MESSAGE_CAMERADATAREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace camera_pkg
{
template <class ContainerAllocator>
struct CameraDataRequest_
{
  typedef CameraDataRequest_<ContainerAllocator> Type;

  CameraDataRequest_()
    : num(0)
    , stitches()  {
    }
  CameraDataRequest_(const ContainerAllocator& _alloc)
    : num(0)
    , stitches(_alloc)  {
  (void)_alloc;
    }



   typedef int64_t _num_type;
  _num_type num;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _stitches_type;
  _stitches_type stitches;





  typedef boost::shared_ptr< ::camera_pkg::CameraDataRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::camera_pkg::CameraDataRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CameraDataRequest_

typedef ::camera_pkg::CameraDataRequest_<std::allocator<void> > CameraDataRequest;

typedef boost::shared_ptr< ::camera_pkg::CameraDataRequest > CameraDataRequestPtr;
typedef boost::shared_ptr< ::camera_pkg::CameraDataRequest const> CameraDataRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::camera_pkg::CameraDataRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::camera_pkg::CameraDataRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::camera_pkg::CameraDataRequest_<ContainerAllocator1> & lhs, const ::camera_pkg::CameraDataRequest_<ContainerAllocator2> & rhs)
{
  return lhs.num == rhs.num &&
    lhs.stitches == rhs.stitches;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::camera_pkg::CameraDataRequest_<ContainerAllocator1> & lhs, const ::camera_pkg::CameraDataRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace camera_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::camera_pkg::CameraDataRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::camera_pkg::CameraDataRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera_pkg::CameraDataRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera_pkg::CameraDataRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera_pkg::CameraDataRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera_pkg::CameraDataRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::camera_pkg::CameraDataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "728e20175689a0067ab9e0629d227334";
  }

  static const char* value(const ::camera_pkg::CameraDataRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x728e20175689a006ULL;
  static const uint64_t static_value2 = 0x7ab9e0629d227334ULL;
};

template<class ContainerAllocator>
struct DataType< ::camera_pkg::CameraDataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "camera_pkg/CameraDataRequest";
  }

  static const char* value(const ::camera_pkg::CameraDataRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::camera_pkg::CameraDataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 num\n"
"float64[] stitches\n"
;
  }

  static const char* value(const ::camera_pkg::CameraDataRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::camera_pkg::CameraDataRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num);
      stream.next(m.stitches);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CameraDataRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::camera_pkg::CameraDataRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::camera_pkg::CameraDataRequest_<ContainerAllocator>& v)
  {
    s << indent << "num: ";
    Printer<int64_t>::stream(s, indent + "  ", v.num);
    s << indent << "stitches[]" << std::endl;
    for (size_t i = 0; i < v.stitches.size(); ++i)
    {
      s << indent << "  stitches[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.stitches[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAMERA_PKG_MESSAGE_CAMERADATAREQUEST_H
