// Generated by gencpp from file camera_pkg/CameraData.msg
// DO NOT EDIT!


#ifndef CAMERA_PKG_MESSAGE_CAMERADATA_H
#define CAMERA_PKG_MESSAGE_CAMERADATA_H

#include <ros/service_traits.h>


#include <camera_pkg/CameraDataRequest.h>
#include <camera_pkg/CameraDataResponse.h>


namespace camera_pkg
{

struct CameraData
{

typedef CameraDataRequest Request;
typedef CameraDataResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CameraData
} // namespace camera_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::camera_pkg::CameraData > {
  static const char* value()
  {
    return "728e20175689a0067ab9e0629d227334";
  }

  static const char* value(const ::camera_pkg::CameraData&) { return value(); }
};

template<>
struct DataType< ::camera_pkg::CameraData > {
  static const char* value()
  {
    return "camera_pkg/CameraData";
  }

  static const char* value(const ::camera_pkg::CameraData&) { return value(); }
};


// service_traits::MD5Sum< ::camera_pkg::CameraDataRequest> should match
// service_traits::MD5Sum< ::camera_pkg::CameraData >
template<>
struct MD5Sum< ::camera_pkg::CameraDataRequest>
{
  static const char* value()
  {
    return MD5Sum< ::camera_pkg::CameraData >::value();
  }
  static const char* value(const ::camera_pkg::CameraDataRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::camera_pkg::CameraDataRequest> should match
// service_traits::DataType< ::camera_pkg::CameraData >
template<>
struct DataType< ::camera_pkg::CameraDataRequest>
{
  static const char* value()
  {
    return DataType< ::camera_pkg::CameraData >::value();
  }
  static const char* value(const ::camera_pkg::CameraDataRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::camera_pkg::CameraDataResponse> should match
// service_traits::MD5Sum< ::camera_pkg::CameraData >
template<>
struct MD5Sum< ::camera_pkg::CameraDataResponse>
{
  static const char* value()
  {
    return MD5Sum< ::camera_pkg::CameraData >::value();
  }
  static const char* value(const ::camera_pkg::CameraDataResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::camera_pkg::CameraDataResponse> should match
// service_traits::DataType< ::camera_pkg::CameraData >
template<>
struct DataType< ::camera_pkg::CameraDataResponse>
{
  static const char* value()
  {
    return DataType< ::camera_pkg::CameraData >::value();
  }
  static const char* value(const ::camera_pkg::CameraDataResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAMERA_PKG_MESSAGE_CAMERADATA_H
