// Generated by gencpp from file camera_pkg/Otro.msg
// DO NOT EDIT!


#ifndef CAMERA_PKG_MESSAGE_OTRO_H
#define CAMERA_PKG_MESSAGE_OTRO_H

#include <ros/service_traits.h>


#include <camera_pkg/OtroRequest.h>
#include <camera_pkg/OtroResponse.h>


namespace camera_pkg
{

struct Otro
{

typedef OtroRequest Request;
typedef OtroResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Otro
} // namespace camera_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::camera_pkg::Otro > {
  static const char* value()
  {
    return "019706110004b728d56d8baaa8e32797";
  }

  static const char* value(const ::camera_pkg::Otro&) { return value(); }
};

template<>
struct DataType< ::camera_pkg::Otro > {
  static const char* value()
  {
    return "camera_pkg/Otro";
  }

  static const char* value(const ::camera_pkg::Otro&) { return value(); }
};


// service_traits::MD5Sum< ::camera_pkg::OtroRequest> should match
// service_traits::MD5Sum< ::camera_pkg::Otro >
template<>
struct MD5Sum< ::camera_pkg::OtroRequest>
{
  static const char* value()
  {
    return MD5Sum< ::camera_pkg::Otro >::value();
  }
  static const char* value(const ::camera_pkg::OtroRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::camera_pkg::OtroRequest> should match
// service_traits::DataType< ::camera_pkg::Otro >
template<>
struct DataType< ::camera_pkg::OtroRequest>
{
  static const char* value()
  {
    return DataType< ::camera_pkg::Otro >::value();
  }
  static const char* value(const ::camera_pkg::OtroRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::camera_pkg::OtroResponse> should match
// service_traits::MD5Sum< ::camera_pkg::Otro >
template<>
struct MD5Sum< ::camera_pkg::OtroResponse>
{
  static const char* value()
  {
    return MD5Sum< ::camera_pkg::Otro >::value();
  }
  static const char* value(const ::camera_pkg::OtroResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::camera_pkg::OtroResponse> should match
// service_traits::DataType< ::camera_pkg::Otro >
template<>
struct DataType< ::camera_pkg::OtroResponse>
{
  static const char* value()
  {
    return DataType< ::camera_pkg::Otro >::value();
  }
  static const char* value(const ::camera_pkg::OtroResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAMERA_PKG_MESSAGE_OTRO_H
