// Generated by gencpp from file camera_pkg/UserReq.msg
// DO NOT EDIT!


#ifndef CAMERA_PKG_MESSAGE_USERREQ_H
#define CAMERA_PKG_MESSAGE_USERREQ_H

#include <ros/service_traits.h>


#include <camera_pkg/UserReqRequest.h>
#include <camera_pkg/UserReqResponse.h>


namespace camera_pkg
{

struct UserReq
{

typedef UserReqRequest Request;
typedef UserReqResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct UserReq
} // namespace camera_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::camera_pkg::UserReq > {
  static const char* value()
  {
    return "728e20175689a0067ab9e0629d227334";
  }

  static const char* value(const ::camera_pkg::UserReq&) { return value(); }
};

template<>
struct DataType< ::camera_pkg::UserReq > {
  static const char* value()
  {
    return "camera_pkg/UserReq";
  }

  static const char* value(const ::camera_pkg::UserReq&) { return value(); }
};


// service_traits::MD5Sum< ::camera_pkg::UserReqRequest> should match
// service_traits::MD5Sum< ::camera_pkg::UserReq >
template<>
struct MD5Sum< ::camera_pkg::UserReqRequest>
{
  static const char* value()
  {
    return MD5Sum< ::camera_pkg::UserReq >::value();
  }
  static const char* value(const ::camera_pkg::UserReqRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::camera_pkg::UserReqRequest> should match
// service_traits::DataType< ::camera_pkg::UserReq >
template<>
struct DataType< ::camera_pkg::UserReqRequest>
{
  static const char* value()
  {
    return DataType< ::camera_pkg::UserReq >::value();
  }
  static const char* value(const ::camera_pkg::UserReqRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::camera_pkg::UserReqResponse> should match
// service_traits::MD5Sum< ::camera_pkg::UserReq >
template<>
struct MD5Sum< ::camera_pkg::UserReqResponse>
{
  static const char* value()
  {
    return MD5Sum< ::camera_pkg::UserReq >::value();
  }
  static const char* value(const ::camera_pkg::UserReqResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::camera_pkg::UserReqResponse> should match
// service_traits::DataType< ::camera_pkg::UserReq >
template<>
struct DataType< ::camera_pkg::UserReqResponse>
{
  static const char* value()
  {
    return DataType< ::camera_pkg::UserReq >::value();
  }
  static const char* value(const ::camera_pkg::UserReqResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAMERA_PKG_MESSAGE_USERREQ_H
