// Generated by gencpp from file camera_pkg/UserReqRequest.msg
// DO NOT EDIT!


#ifndef CAMERA_PKG_MESSAGE_USERREQREQUEST_H
#define CAMERA_PKG_MESSAGE_USERREQREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace camera_pkg
{
template <class ContainerAllocator>
struct UserReqRequest_
{
  typedef UserReqRequest_<ContainerAllocator> Type;

  UserReqRequest_()
    {
    }
  UserReqRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::camera_pkg::UserReqRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::camera_pkg::UserReqRequest_<ContainerAllocator> const> ConstPtr;

}; // struct UserReqRequest_

typedef ::camera_pkg::UserReqRequest_<std::allocator<void> > UserReqRequest;

typedef boost::shared_ptr< ::camera_pkg::UserReqRequest > UserReqRequestPtr;
typedef boost::shared_ptr< ::camera_pkg::UserReqRequest const> UserReqRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::camera_pkg::UserReqRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::camera_pkg::UserReqRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace camera_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::camera_pkg::UserReqRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::camera_pkg::UserReqRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera_pkg::UserReqRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera_pkg::UserReqRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera_pkg::UserReqRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera_pkg::UserReqRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::camera_pkg::UserReqRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::camera_pkg::UserReqRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::camera_pkg::UserReqRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "camera_pkg/UserReqRequest";
  }

  static const char* value(const ::camera_pkg::UserReqRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::camera_pkg::UserReqRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::camera_pkg::UserReqRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::camera_pkg::UserReqRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UserReqRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::camera_pkg::UserReqRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::camera_pkg::UserReqRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // CAMERA_PKG_MESSAGE_USERREQREQUEST_H
