// Generated by gencpp from file first_pkg/CameraData.msg
// DO NOT EDIT!


#ifndef FIRST_PKG_MESSAGE_CAMERADATA_H
#define FIRST_PKG_MESSAGE_CAMERADATA_H

#include <ros/service_traits.h>


#include <first_pkg/CameraDataRequest.h>
#include <first_pkg/CameraDataResponse.h>


namespace first_pkg
{

struct CameraData
{

typedef CameraDataRequest Request;
typedef CameraDataResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CameraData
} // namespace first_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::first_pkg::CameraData > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::first_pkg::CameraData&) { return value(); }
};

template<>
struct DataType< ::first_pkg::CameraData > {
  static const char* value()
  {
    return "first_pkg/CameraData";
  }

  static const char* value(const ::first_pkg::CameraData&) { return value(); }
};


// service_traits::MD5Sum< ::first_pkg::CameraDataRequest> should match
// service_traits::MD5Sum< ::first_pkg::CameraData >
template<>
struct MD5Sum< ::first_pkg::CameraDataRequest>
{
  static const char* value()
  {
    return MD5Sum< ::first_pkg::CameraData >::value();
  }
  static const char* value(const ::first_pkg::CameraDataRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::first_pkg::CameraDataRequest> should match
// service_traits::DataType< ::first_pkg::CameraData >
template<>
struct DataType< ::first_pkg::CameraDataRequest>
{
  static const char* value()
  {
    return DataType< ::first_pkg::CameraData >::value();
  }
  static const char* value(const ::first_pkg::CameraDataRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::first_pkg::CameraDataResponse> should match
// service_traits::MD5Sum< ::first_pkg::CameraData >
template<>
struct MD5Sum< ::first_pkg::CameraDataResponse>
{
  static const char* value()
  {
    return MD5Sum< ::first_pkg::CameraData >::value();
  }
  static const char* value(const ::first_pkg::CameraDataResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::first_pkg::CameraDataResponse> should match
// service_traits::DataType< ::first_pkg::CameraData >
template<>
struct DataType< ::first_pkg::CameraDataResponse>
{
  static const char* value()
  {
    return DataType< ::first_pkg::CameraData >::value();
  }
  static const char* value(const ::first_pkg::CameraDataResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FIRST_PKG_MESSAGE_CAMERADATA_H
